version: '3.8'

services:
  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu_lab3
    user: root
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - "./:/home/user/lab3_files"
